---

- name: Manage User Account

  hosts: workers

  become: true

  gather_facts: false

  tasks:

    - name: Create User.

      user:

        name: "{{ item }}"

        shell: /bin/bash

        state: present

      loop:

        - user1

        - user2

        - user3
